name: Deploy portfolio
permissions:
  contents: write
  
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo run
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
